<!-- Headings --><!-- strong--><span style='color:Green'> Python Week 5 Homework </span>
<!-- OL-->
1. What does Pandas stand for?<span style='color:Green'> An open-source Python package that is most widely used for data science/data analysis and machine learning tasks. </span>

2. What are the 2 collections used in Pandas?<span style='color:Green'> The 2 collections used in Pandas are Series and Dataframes. </span>
3. Name 4 things Pandas can do for us.<span style='color:Green'> The 4 things Pandas can do are:
Data Cleansing/	Data fill,
Data normalization/	Merges and joins,
Data visualization/	Statistical analysis and
Data inspection/	Loading and saving data. </span>
4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?<span style='color:Green'> The keyword that should be used with df.sort is values. </span>
5. What is a CSV<span style='color:Green'> CSV (comma separated files) is a simple way to store big data sets in plain text and is a well know format that can be read by everyone. </span>
6. When cleaning data what values do we not like in our data? <span style='color:Green'> When cleaning data, the values that the least like are NULLs. </span>

In [104]:

#1.  Concatenate these 3 arrays into a new array named 'newArray'...
import numpy as np

array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray= np.concatenate((array1, array2, array3), axis=0)

#2.  Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)

#3.  Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.
newShape = sortedArray.reshape(2, 2, 3)
print(newShape)

#4.  Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
tuple1 = ([[25, 16]],
[[11, 2], [13, 4]],
[[7, 81], [5, 6], [11, 12]])

a, b , c = tuple1
print(a, b, c)
print("The data type of c ...", type(c))

#5.  Combined and sort the following arrays into one called 'comboArray' ...
import numpy as np

arrayG= np.array([10, 11, 12, 13, 14, 15, 16, 17])
arrayH = np.array([20, 21, 22, 23, 24, 25, 26, 27])
arrayI = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])
combo1 = np.concatenate((arrayG, arrayH, arrayI), axis=0) 
comboArray=(np.sort(combo1))
   
#6.  Take 'comboArray' and perform the following slicing activities:
# print sec1 - the 2nd element
print(comboArray[2])
# print sec2 - all elements from the 3rd element to the last
print(comboArray[3:26])
# print sec3 - all elements from the 4th to the 14th elements
print(comboArray[4:15])
# print sec4 - the last 6 elements
print(comboArray[-6:26])
# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[-26:-10])
# print sec6 - from #20 every even element to the end
print(comboArray[20::2])
# print sec7 - from the last element moving forward, every 5th element.
print(comboArray[23::5])

# 7. Using simple math operations, broadcast the addition (+), division (/), and multiplication (*) operations for these 2 arrays --
from numpy import array

arr1 = array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
                [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
                [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

arr2 = array([[17.0, 70.0, 10.7]])

print("Addition", arr1 + arr2)
print("Multiplication", arr1 * arr2)
print("Division", arr1 / arr2)
#8. Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7.
import numpy as np
arr1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
                [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
                [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

arr2 = np.array([[17.0, 70.0, 10.7]])

arrS= np.subtract(arr1 , arr2)
#9. Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.
divisible_by_3 = arr1[arr1 % 3 == 0]
# print("arr1 elements divisible_by_3 ...", divisible_by_3)

#10. Using Series, create a DataFrame that looks like this:

import pandas as pd

Ingredients = pd.Series(["Flour","Milk","Eggs", "Spam"], name ='Ingredients')
Quantity = pd.Series([4, 1, 2, 1], name = 'Quantity')
Unit  = pd.Series(["cups", "cup", "large", "can"], name = 'Unit')

Dinner = pd.concat([Ingredients, Quantity, Unit], axis=1)
# print(Dinner)

#11. Take this data and create a DataFrame named studentData
import pandas as pd

data ={'Name': ['Jai', 'Janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
       'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}

studentData= pd.DataFrame(data, columns=['Name', 'Height',
                                     'Qualification', 'Address', 'Age', 'Pets', 'Sport'])
# print(studentData)

#12. Add a new column to the DataFrame with the following deserts: 
studentData.insert(2, 'Deserts', ['Ice cream', 'Cashew Fudge', 'Waffels', 'Carrot Halwa'], True)

#13. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentData.sort_values(["Name", "Address"],
               ascending = [True, True])

#14. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
studentData.to_csv('cows_and_goats.csv')
studentData = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
print(studentData)

#15. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
import pandas as pd

Veggies ={'Vegetables': ['Tomato', 'Broccoli', 'Cabbage', 'Carrot'], 
        'Calories': [20, 207, 227, 25],
       'Servings': ['111g', '608g', '908g', '61g'],
        'Colors': ['Red', 'Green', 'Green', 'Orange']}

healthfoodData= pd.DataFrame(Veggies, columns=['Vegetables', 'Calories', 'Servings','Color'])

healthfoodData.to_csv('Dietplan.csv')
newplan=healthfoodData.replace(to_replace = 'Cabbage',
                        value = 'Kale')
newplan.to_csv('New Diet Plan')


[[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]
[[25, 16]] [[11, 2], [13, 4]] [[7, 81], [5, 6], [11, 12]]
The data type of c ... <class 'list'>
2
[ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[24 26]
[27]
Addition [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]
Multiplication [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]
Division [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]
      